---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum:
    name: "{{ item }}"
    state: installed
  loop:
   - mariadb-server
   - MySQL-python
  when: ansible_os_family == "RedHat"

- name: Configure SELinux to start mysql on any port
  seboolean: 
    name: mysql_connect_any
    state: true
    persistent: yes
  when: ansible_os_family == "RedHat"

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mariadb
  when: ansible_os_family == "RedHat"

- name: Create MariaDB log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0775
  when: ansible_os_family == "RedHat"

- name: Create MariaDB PID directory
  file:
    path: /var/run/mysqld
    state: directory
    owner: mysql
    group: mysql
    mode: 0775
  when: ansible_os_family == "RedHat"

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: insert firewalld rule
  firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"

- name: Create Application Database
  mysql_db: 
    name: "{{ dbname }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Create Application DB User
  mysql_user: 
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  when: ansible_os_family == "RedHat"

- name: Install MariaDB package
  apt:
    name: "{{ item }}"
    state: present
  loop:
   - mariadb-server
   - python3-pymysql
  when: ansible_os_family == "Debian"

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mariadb
  when: ansible_os_family == "Debian"

- name: Create MariaDB log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0775
  when: ansible_os_family == "Debian"

- name: Create MariaDB PID directory
  file:
    path: /var/run/mysqld
    state: directory
    owner: mysql
    group: mysql
    mode: 0775
  when: ansible_os_family == "Debian"

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Start ufw
  service:
    name: ufw
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: insert firewalld rule
  ufw:
    port: "{{ mysql_port }}/tcp"
    state: enabled
  when: ansible_os_family == "Debian"

- name: Create Application Database
  mysql_db:
    name: "{{ dbname }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  when: ansible_os_family == "Debian"
